### ISSUE TITLE
List of available config parameters?

### ISSUE THREAD

**Issue by laurin1** [YvesR/mod_authn_ntlm#14]
I apologize up for using an Issue to ask this question, but I cannot find an exhaustive list of parameters for this module anywhere. I pariticularly want to know about NTLMDefaultDomain and how that works.

**Comment by YvesR** [comment]
`NTLMDefaultDomain` is needed if you want to specify the domain or domain controller to check against. So it adds this domain to your username before authenticate.
If you user send username@domain with his browser this domain will be overwritten.

**Comment by laurin1** [comment]
Ok, thanks, but is there a "complete" list somewhere?

**Comment by JBlond** [comment]
Yes there is a complete list
https://github.com/YvesR/mod_authn_ntlm/blob/master/src/mod_ntlm.c Lines 38 - 91

- `NTLMAuth` => set to 'on' to activate NTLM authentication here
- `NTLMOfferNTLM` => set to 'off' to allow access control to be passed along to lower modules if the UserID is not known to this module
- `NTLMAuthoritative` => set to 'off' to allow access control to be passed along to lower modules if the UserID is not known to this module
- `NTLMOfferBasic` => set to 'on' to allow the client to authenticate against NT with 'Basic' authentication instead of using the NTLM protocol
- `NTLMPackage` => set to the name of the package you want to use to authenticate users
- `NTLMPackages` => set to the name of the package you want to use to authenticate users
- `NTLMDomain` => set to the domain you want users authenticated against for cleartext authentication - if not specified, the local machine, then all trusted domains are checked
- `NTLMOmitDomain` => set to 'on' if you want the usernames to have the domain set to 'on' if you want the usernames to have the domain
- `NTLMUsernameCase` => set to 'lower' if you want the username and domain to be lowercase, set to 'upper' if you want the username and domain to be uppercase, if not specified, username and domain case conversion is disabled
- `NTLMBasicPreferred` => set to 'on' if you want basic authentication to be the higher priority
- `NTLMMSIE3Hack` => set to 'on' if you expect MSIE 3 clients to be using this server
- `NTLMPerRequestAuth` => set to 'on' if you want authorization per request instead of per connection
- `NTLMChainAuth` => set to 'on' if you want an alternative authorization module like SVNPathAuthz to work at the same level
- `NTLMNotForced` => Set to on to allow requests pass even when user not really authorized This is needed if same resources can be access with and without NTLM auth

**Comment by laurin1** [comment]
Thank you!

**Comment by JBlond** [comment]
@YvesR it might be good to add that list to the readme or a separat file.

**Comment by YvesR** [comment]
Good idea, updated the readme file.
